service:
  name: Facebook Chatbot APIs Documentation
  description: API specification for Facebook Chatbot || baseUrl="/api/v1"
  apiVersion: 0.1.0
  docsBaseUrl: /docs/api
  baseUrl: /api/v1

server:
  keepAlive: 80000
  cors:
    allowedHeaders: 'authorization,content-type'
    exposedHeaders: 'authorization,x-response-time,x-request-id, x-pagination-page, x-pagination-page-size, x-pagination-total'